"""reward_design check — is the reward function *shaped* well for RL?

A reward can be deterministic and unexploitable and still be a bad training
signal. This check audits the reward's *design*:

* **weights** (no model) — all-zero weights mean the reward is 0 by construction;
  negative weights are surfaced for review.
* **discrimination** — does a correct answer score above wrong/garbage? If not,
  the policy gradient points nowhere.
* **baseline floor** — does every response earn a constant positive reward? A
  flat floor dilutes the learnable signal.
* **signal type** — constant / binary / graded (graded usually trains better).
* **bounds** — rewards far outside [0, 1] complicate advantage normalization.

The behavioral probes (gold / gold_rewritten / partial / wrong / garbage in this
env's own answer format) are generated by a model via ``skills/reward_design.md``,
so the check works on any env type. Each finding maps to a recommendation (see
REWARD_DESIGN.md). The weight check runs without a model; the behavioral part
needs an endpoint and SKIPs without one (no static fallback by design).
"""

from __future__ import annotations

from rlenv_audit.adapters.verifiers import EnvHandle, ScoringError
from rlenv_audit.checks.base import CheckResult, CheckSpec, CheckStatus
from rlenv_audit.skills import endpoint_configured, run_skill

_EPS = 1e-9
_GOLD_KINDS = {"gold", "gold_rewritten"}
_JUNK_KINDS = {"wrong", "garbage"}


def check_reward_design(handle: EnvHandle, config: dict) -> CheckResult:
    n_tasks = int(config.get("reward_design_tasks", 5))

    # ---- structural facts about the rubric (no model needed) -------------
    func_names = handle.reward_func_names()
    try:
        weights = list(handle.rubric._get_reward_weights()) if handle.rubric else []
    except Exception:
        weights = []
    nonzero_weights = [w for w in weights if abs(w) > _EPS]
    negative_weights = [w for w in weights if w < 0]

    if weights and not nonzero_weights:
        return CheckResult(
            "reward_design", CheckStatus.FAIL,
            "all reward weights are zero — the aggregate reward is 0 by construction",
            score=0.0,
            details={
                "reward_funcs": func_names, "weights": weights,
                "recommendations": [
                    "Give at least one reward function a non-zero weight; with all "
                    "weights zero the policy receives no signal (REWARD_DESIGN.md §weights)."
                ],
            },
        )

    if not endpoint_configured(config):
        return CheckResult(
            "reward_design", CheckStatus.SKIP,
            "reward-shape probing needs a model endpoint to generate completions "
            "(set OPENAI_API_KEY / OPENAI_BASE_URL or pass --endpoint); weights look ok",
            details={"reward_funcs": func_names, "weights": weights},
        )

    rows = handle.dataset(n=n_tasks)
    if not rows:
        return CheckResult("reward_design", CheckStatus.SKIP, "environment exposes no dataset")

    skill = run_skill(handle, config, "reward_design", rows)
    probes = (skill or {}).get("probes") or []
    by_task: dict[int, list[dict]] = {}
    for p in probes:
        if not isinstance(p, dict) or not isinstance(p.get("text"), str):
            continue
        try:
            ti = max(0, min(int(p.get("task_index", 0)), len(rows) - 1))
        except (TypeError, ValueError):
            ti = 0
        by_task.setdefault(ti, []).append(p)
    if not by_task:
        return CheckResult(
            "reward_design", CheckStatus.SKIP,
            "model did not generate any reward-design probes for this environment",
            details={"raw": skill},
        )

    # ---- behavioral probe -------------------------------------------------
    recommendations: list[str] = []
    warnings: list[str] = []
    per_task: list[dict] = []
    all_rewards: list[float] = []
    discriminating = 0
    probed = 0
    floors: list[float] = []
    has_gold = False

    for ti, plist in sorted(by_task.items()):
        row = rows[ti]
        prompt, info, cols = row["prompt"], row["info"], row.get("raw", {})

        def score(text: str) -> float | None:
            try:
                r, _ = handle.score(text, prompt, row["answer"], info, cols)
                return r
            except ScoringError:
                return None

        scored: dict[str, float] = {}
        kinds: dict[str, str] = {}
        for p in plist:
            label = f"{p.get('kind', '?')}:{p.get('label', '')}"
            r = score(p["text"])
            if r is not None:
                scored[label] = r
                kinds[label] = p.get("kind", "")
        # a universal empty-string floor probe (format-agnostic, not a battery)
        empty_r = score("")
        if empty_r is not None:
            scored["empty"] = empty_r
            kinds["empty"] = "garbage"

        if not scored:
            per_task.append({"task": ti, "error": "no probe could be scored"})
            continue

        probed += 1
        all_rewards.extend(scored.values())
        gold = max((v for k, v in scored.items() if kinds.get(k) in _GOLD_KINDS), default=None)
        junk = max((v for k, v in scored.items() if kinds.get(k) in _JUNK_KINDS), default=0.0)
        floors.append(junk)
        if gold is not None:
            has_gold = True
            if gold > junk + _EPS:
                discriminating += 1
        per_task.append(
            {"task": ti, "rewards": {k: round(v, 6) for k, v in scored.items()},
             "gold_max": gold, "junk_max": junk}
        )

    if probed == 0:
        return CheckResult(
            "reward_design", CheckStatus.SKIP,
            "none of the generated probes could be scored through the rubric",
            details={"per_task": per_task},
        )

    distinct = sorted({round(r, 6) for r in all_rewards})
    rmin, rmax = min(all_rewards), max(all_rewards)
    signal_type = "constant" if len(distinct) == 1 else "binary" if len(distinct) == 2 else "graded"
    discrimination_rate = discriminating / probed if has_gold else None
    flat_floor = bool(floors) and min(floors) > _EPS

    base_details = {
        "model": (skill or {}).get("_model"),
        "reward_funcs": func_names, "weights": weights,
        "signal_type": signal_type, "reward_range": [rmin, rmax],
        "discrimination_rate": discrimination_rate,
        "baseline_floor": min(floors) if floors else None,
        "tasks_probed": probed, "probes_generated": len(probes),
        "per_task": per_task,
    }

    if signal_type == "constant":
        recommendations.append(
            "The reward returns the same value for correct, wrong, and garbage "
            "completions. If scoring needs a live service (judge/API), document it; "
            "otherwise the verifier is not reading the completion "
            "(REWARD_DESIGN.md §discrimination)."
        )
        status = CheckStatus.FAIL if abs(distinct[0]) > _EPS else CheckStatus.WARN
        msg = f"reward is constant ({distinct[0]}) for every probe — gold, wrong, and garbage all score the same"
        return CheckResult(
            "reward_design", status,
            msg if status is CheckStatus.FAIL else msg + " (all zero — may need a live judge/service)",
            score=0.0, details={**base_details, "recommendations": recommendations},
        )

    if discrimination_rate is not None and discrimination_rate < 0.5:
        warnings.append(f"reward separated gold from junk on only {discriminating}/{probed} tasks")
        recommendations.append(
            "Correct answers often score no better than garbage. Check the parser/"
            "matcher accepts the dataset's own gold answers — if the env can't reward "
            "its own answer key, a policy can't learn from it (REWARD_DESIGN.md §discrimination)."
        )
    if flat_floor:
        warnings.append(f"every response earns a baseline reward (floor {min(floors):.3g})")
        recommendations.append(
            "Remove constant participation/format rewards or weight them near zero: a "
            "flat floor shrinks the relative advantage of solving the task "
            "(REWARD_DESIGN.md §baseline-floor)."
        )
    if rmax > 1.0 + 1e-6 or rmin < -1e-6:
        warnings.append(f"reward range [{rmin:.3g}, {rmax:.3g}] outside [0, 1]")
        recommendations.append(
            "Normalize the aggregate reward into [0, 1] (or document the range): unbounded "
            "rewards complicate advantage normalization (REWARD_DESIGN.md §bounds)."
        )
    if negative_weights:
        warnings.append(f"{len(negative_weights)} reward weight(s) are negative")
        recommendations.append(
            "Negative-weight penalties are easy to get backwards — confirm each penalty "
            "can't dominate the positive signal (REWARD_DESIGN.md §weights)."
        )
    if signal_type == "binary":
        recommendations.append(
            "Reward is strictly 0-or-1. That's valid, but graded partial credit usually "
            "gives the policy a denser gradient on hard tasks (REWARD_DESIGN.md §partial-credit)."
        )

    details = {**base_details, "recommendations": recommendations}
    score = discrimination_rate

    if warnings:
        return CheckResult(
            "reward_design", CheckStatus.WARN,
            "; ".join(warnings) + f" (signal: {signal_type})",
            score=score, details=details,
        )
    return CheckResult(
        "reward_design", CheckStatus.PASS,
        f"{signal_type} reward, separates gold from junk on "
        f"{discriminating}/{probed} tasks, range [{rmin:.2g}, {rmax:.2g}]",
        score=score, details=details,
    )


SPEC = CheckSpec(
    name="reward_design",
    func=check_reward_design,
    description="reward shape: discrimination, baseline floor, signal type, bounds, weights",
    needs_gpu=False,
    needs_docker=False,
    needs_model=True,
)
